/**
* Copyright (c) NVIDIA CORPORATION & AFFILIATES, 2001-2018. ALL RIGHTS RESERVED.
*
* See file LICENSE for terms.
*/

#ifndef UCS_PROFILE_ON_H_
#define UCS_PROFILE_ON_H_

#include "profile_defs.h"

#define UCS_PROFILE_SAMPLE                          UCS_PROFILE_SAMPLE_ALWAYS
#define UCS_PROFILE_CODE                            UCS_PROFILE_CODE_ALWAYS
#define UCS_PROFILE_FUNC                            UCS_PROFILE_FUNC_ALWAYS
#define UCS_PROFILE_FUNC_VOID                       UCS_PROFILE_FUNC_VOID_ALWAYS
#define UCS_PROFILE_NAMED_CALL                      UCS_PROFILE_NAMED_CALL_ALWAYS
#define UCS_PROFILE_CALL                            UCS_PROFILE_CALL_ALWAYS
#define UCS_PROFILE_NAMED_CALL_VOID                 UCS_PROFILE_NAMED_CALL_VOID_ALWAYS
#define UCS_PROFILE_CALL_VOID                       UCS_PROFILE_CALL_VOID_ALWAYS
#define UCS_PROFILE_REQUEST_NEW                     UCS_PROFILE_REQUEST_NEW_ALWAYS
#define UCS_PROFILE_REQUEST_EVENT                   UCS_PROFILE_REQUEST_EVENT_ALWAYS
#define UCS_PROFILE_REQUEST_EVENT_CHECK_STATUS      UCS_PROFILE_REQUEST_EVENT_CHECK_STATUS_ALWAYS
#define UCS_PROFILE_REQUEST_FREE                    UCS_PROFILE_REQUEST_FREE_ALWAYS
#define UCS_PROFILE_CLASS_INIT_FUNC                 UCS_PROFILE_CLASS_INIT_FUNC_ALWAYS
#define UCS_PROFILE_CLASS_CLEANUP_FUNC              UCS_PROFILE_CLASS_CLEANUP_FUNC_ALWAYS
#define UCS_PROFILE_CLASS_DEFINE_NAMED_DELETE_FUNC  UCS_PROFILE_CLASS_DEFINE_NAMED_DELETE_FUNC_ALWAYS
#define UCS_PROFILE_CLASS_DEFINE_DELETE_FUNC        UCS_PROFILE_CLASS_DEFINE_DELETE_FUNC_ALWAYS

#endif
